require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlbumStatusesController do

  # This should return the minimal set of attributes required to create a valid
  # AlbumStatus. As you add validations to AlbumStatus, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all album_statuses as @album_statuses" do
      album_status = AlbumStatus.create! valid_attributes
      get :index
      assigns(:album_statuses).should eq([album_status])
    end
  end

  describe "GET show" do
    it "assigns the requested album_status as @album_status" do
      album_status = AlbumStatus.create! valid_attributes
      get :show, :id => album_status.id.to_s
      assigns(:album_status).should eq(album_status)
    end
  end

  describe "GET new" do
    it "assigns a new album_status as @album_status" do
      get :new
      assigns(:album_status).should be_a_new(AlbumStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested album_status as @album_status" do
      album_status = AlbumStatus.create! valid_attributes
      get :edit, :id => album_status.id.to_s
      assigns(:album_status).should eq(album_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlbumStatus" do
        expect {
          post :create, :album_status => valid_attributes
        }.to change(AlbumStatus, :count).by(1)
      end

      it "assigns a newly created album_status as @album_status" do
        post :create, :album_status => valid_attributes
        assigns(:album_status).should be_a(AlbumStatus)
        assigns(:album_status).should be_persisted
      end

      it "redirects to the created album_status" do
        post :create, :album_status => valid_attributes
        response.should redirect_to(AlbumStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved album_status as @album_status" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumStatus.any_instance.stub(:save).and_return(false)
        post :create, :album_status => {}
        assigns(:album_status).should be_a_new(AlbumStatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumStatus.any_instance.stub(:save).and_return(false)
        post :create, :album_status => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested album_status" do
        album_status = AlbumStatus.create! valid_attributes
        # Assuming there are no other album_statuses in the database, this
        # specifies that the AlbumStatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlbumStatus.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => album_status.id, :album_status => {'these' => 'params'}
      end

      it "assigns the requested album_status as @album_status" do
        album_status = AlbumStatus.create! valid_attributes
        put :update, :id => album_status.id, :album_status => valid_attributes
        assigns(:album_status).should eq(album_status)
      end

      it "redirects to the album_status" do
        album_status = AlbumStatus.create! valid_attributes
        put :update, :id => album_status.id, :album_status => valid_attributes
        response.should redirect_to(album_status)
      end
    end

    describe "with invalid params" do
      it "assigns the album_status as @album_status" do
        album_status = AlbumStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumStatus.any_instance.stub(:save).and_return(false)
        put :update, :id => album_status.id.to_s, :album_status => {}
        assigns(:album_status).should eq(album_status)
      end

      it "re-renders the 'edit' template" do
        album_status = AlbumStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumStatus.any_instance.stub(:save).and_return(false)
        put :update, :id => album_status.id.to_s, :album_status => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested album_status" do
      album_status = AlbumStatus.create! valid_attributes
      expect {
        delete :destroy, :id => album_status.id.to_s
      }.to change(AlbumStatus, :count).by(-1)
    end

    it "redirects to the album_statuses list" do
      album_status = AlbumStatus.create! valid_attributes
      delete :destroy, :id => album_status.id.to_s
      response.should redirect_to(album_statuses_url)
    end
  end

end
