require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArtistsController do

  # This should return the minimal set of attributes required to create a valid
  # Artist.
  def valid_create_attributes
    FactoryGirl.attributes_for(:artist)
  end

  # This should return the minimal set of attributes required to update a valid
  # Artist.
  def valid_update_attributes
    FactoryGirl.attributes_for(:artist)
  end

  describe "GET index" do
    context  do # Within default nesting

      context 'without a user session' do
        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :index, {}
          end
          it { should redirect_to(new_user_session_path) }
          it { should set_the_flash[:alert].to("You need to sign in or sign up before continuing.") }
        end
      end
      context 'as an unauthorized user' do
        login_unauthorized_user

        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :index, {}
          end
          it { should redirect_to(root_url) }
          it { should set_the_flash[:alert].to("You are not authorized to access this page.") }
        end
      end
      context 'as user with read ability' do
        login_user_with_ability :read, Artist

        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :index, {}
          end
          it { should respond_with(:success) }
          it { should render_template(:index) }
          it { should render_with_layout(:application) }
          it "assigns all artists as @artists" do
            assigns(:artists).should eq([@test_artist])
          end
        end
      end
    end
  end

  describe "GET show" do
    context  do # Within default nesting

      context 'without a user session' do
        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :show, {:id => @test_artist.to_param}
          end
          it { should redirect_to(new_user_session_path) }
          it { should set_the_flash[:alert].to("You need to sign in or sign up before continuing.") }
        end
      end
      context 'as an unauthorized user' do
        login_unauthorized_user

        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :show, {:id => @test_artist.to_param}
          end
          it { should redirect_to(artists_url) }
          it { should set_the_flash[:alert].to("You are not authorized to access this page.") }
        end
      end
      context 'as user with read ability' do
        login_user_with_ability :read, Artist

        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :show, {:id => @test_artist.to_param}
          end
          it { should respond_with(:success) }
          it { should render_template(:show) }
          it { should render_with_layout(:application) }
          it "assigns the requested artist as @artist" do
            assigns(:artist).should eq(@test_artist)
          end
        end
      end
    end
  end

  describe "GET new" do
    context  do # Within default nesting

      context 'without a user session' do
        describe 'with a valid request' do
          before(:each) do
            get :new, {}
          end
          it { should redirect_to(new_user_session_path) }
          it { should set_the_flash[:alert].to("You need to sign in or sign up before continuing.") }
        end
      end
      context 'as an unauthorized user' do
        login_unauthorized_user

        describe 'with a valid request' do
          before(:each) do
            get :new, {}
          end
          it { should redirect_to(artists_url) }
          it { should set_the_flash[:alert].to("You are not authorized to access this page.") }
        end
      end
      context 'as user with create ability' do
        login_user_with_ability :create, Artist

        describe 'with a valid request' do
          before(:each) do
            get :new, {}
          end
          it { should respond_with(:success) }
          it { should render_template(:new) }
          it { should render_with_layout(:application) }
          it "assigns a new artist as @artist" do
            assigns(:artist).should be_a_new(Artist)
          end
        end
      end
    end
  end

  describe "GET edit" do
    context  do # Within default nesting

      context 'without a user session' do
        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :edit, {:id => @test_artist.to_param}
          end
          it { should redirect_to(new_user_session_path) }
          it { should set_the_flash[:alert].to("You need to sign in or sign up before continuing.") }
        end
      end
      context 'as an unauthorized user' do
        login_unauthorized_user

        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :edit, {:id => @test_artist.to_param}
          end
          it { should redirect_to(artists_url) }
          it { should set_the_flash[:alert].to("You are not authorized to access this page.") }
        end
      end
      context 'as user with update ability' do
        login_user_with_ability :update, Artist

        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            get :edit, {:id => @test_artist.to_param}
          end
          it { should respond_with(:success) }
          it { should render_template(:edit) }
          it { should render_with_layout(:application) }
          it "assigns the requested artist as @artist" do
            assigns(:artist).should eq(@test_artist)
          end
        end
      end
    end
  end

  describe "POST create" do
    context  do # Within default nesting

      context 'without a user session' do
        describe 'with a valid request' do
          before(:each) do
            post :create, {:artist => valid_create_attributes}
          end
          it { should redirect_to(new_user_session_path) }
          it { should set_the_flash[:alert].to("You need to sign in or sign up before continuing.") }
        end
      end
      context 'as an unauthorized user' do
        login_unauthorized_user

        describe "with a valid request" do
          before(:each) do
            post :create, {:artist => valid_create_attributes}
          end
          it { should redirect_to(artists_url) }
          it { should set_the_flash[:alert].to("You are not authorized to access this page.") }
        end
      end
      context 'as user with create ability' do
        login_user_with_ability :create, Artist

        describe "with valid params" do
          it "creates a new Artist" do
            expect {
              post :create, {:artist => valid_create_attributes}
            }.to change(Artist, :count).by(1)
          end
        end
        describe 'with a valid request' do
          before(:each) do
            post :create, {:artist => valid_create_attributes}
          end
          it "assigns a newly created artist as @artist" do
            assigns(:artist).should be_a(Artist)
            assigns(:artist).should be_persisted
          end
          it { should set_the_flash[:notice].to('Artist was successfully created.') }
          it "redirects to the created artist" do
            response.should redirect_to(artist_path(Artist.last))
          end
        end
        describe "with an invalid request" do
          before(:each) do
            # Trigger the behavior that occurs when invalid params are submitted
            Artist.any_instance.stub(:save).and_return(false)
            post :create, {:artist => { "name" => "invalid value" }}
          end
          it { should render_template(:new) }
          it { should render_with_layout(:application) }
          it "assigns a newly created but unsaved artist as @artist" do
            assigns(:artist).should be_a_new(Artist)
          end
        end
      end
    end
  end

  describe "PUT update" do
    context  do # Within default nesting

      context 'without a user session' do
        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            put :update, {:id => @test_artist.to_param, :artist => valid_update_attributes}
          end
          it { should redirect_to(new_user_session_path) }
          it { should set_the_flash[:alert].to("You need to sign in or sign up before continuing.") }
        end
      end
      context 'as an unauthorized user' do
        login_unauthorized_user

        describe "with a valid request" do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            put :update, {:id => @test_artist.to_param, :artist => valid_update_attributes}
          end
          it { should redirect_to(artists_url) }
          it { should set_the_flash[:alert].to("You are not authorized to access this page.") }
        end
      end
      context 'as user with update ability' do
        login_user_with_ability :update, Artist

        describe "with valid params" do
          it "updates the requested artist" do
            @test_artist = FactoryGirl.create(:artist)
            # Assuming there are no other artist in the database, this
            # specifies that the Artist created on the previous line
            # receives the :update_attributes message with whatever params are
            # submitted in the request.
            Artist.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
            put :update, {:id => @test_artist.to_param, :artist => { "name" => "MyString" }}
          end
        end
        describe "with a valid request" do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            put :update, {:id => @test_artist.to_param, :artist => valid_update_attributes}
          end
          it "assigns the requested artist as @artist" do
            assigns(:artist).should eq(@test_artist)
          end
          it { should set_the_flash[:notice].to('Artist was successfully updated.') }
          it "redirects to the artist" do
            response.should redirect_to(artist_path(@test_artist))
          end
        end
        describe "with an invalid request" do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            # Trigger the behavior that occurs when invalid params are submitted
            Artist.any_instance.stub(:save).and_return(false)
            put :update, {:id => @test_artist.to_param, :artist => { "name" => "invalid value" }}
          end
          it { should render_template(:edit) }
          it { should render_with_layout(:application) }
          it "assigns the artist as @artist" do
            assigns(:artist).should eq(@test_artist)
          end
        end
      end
    end
  end

  describe "DELETE destroy" do
    context  do # Within default nesting

      context 'without a user session' do
        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            delete :destroy, {:id => @test_artist.to_param}
          end
          it { should redirect_to(new_user_session_path) }
          it { should set_the_flash[:alert].to("You need to sign in or sign up before continuing.") }
        end
      end
      context 'as an unauthorized user' do
        login_unauthorized_user

        describe "with a valid request" do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            delete :destroy, {:id => @test_artist.to_param}
          end
          it { should redirect_to(artists_url) }
          it { should set_the_flash[:alert].to("You are not authorized to access this page.") }
        end
      end
      context 'as user with destroy ability' do
        login_user_with_ability :destroy, Artist

        it "destroys the requested artist" do
          @test_artist = FactoryGirl.create(:artist)
          expect {
            delete :destroy, {:id => @test_artist.to_param}
          }.to change(Artist, :count).by(-1)
        end
        describe 'with a valid request' do
          before(:each) do
            @test_artist = FactoryGirl.create(:artist)
            delete :destroy, {:id => @test_artist.to_param}
          end
          it { should set_the_flash[:notice].to('Artist was successfully deleted.') }
          it "redirects to the artist list" do
            response.should redirect_to(artists_url)
          end
        end
      end
    end
  end

end
